language: java
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS teste;'
  - mysql -e "CREATE USER 'teste'@'localhost' IDENTIFIED BY '1234';"
  - mysql -e "INSERT INTO teste.teste (`nome`, `idade`) VALUES ('Daniel', 27);"
jdk:
 - oraclejdk8
